config/routes.rb
Rails.application.routes.draw do

  root 'gossips#index'
  resources :gossips


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def home
   render html: "hello gossip"
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
    @gossips = Gossip.all
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip =  Gossip.new(gossip_params)
    @gossip.save
    #fait appel à la fonction show avec l'id du gossip
    redirect_to @gossip
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(gossip_params)
    redirect_to @gossip
  end

  def destroy
    Gossip.find(params[:id]).destroy
    redirect_to gossips_path
  end





  private
    def gossip_params
      params.require(:gossip).permit(:anonymous_author, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<h1>Modifier Gossip n° <%= @gossip.id %></h1>

<%= form_with(model: @gossip, local: true) do |form| %>



  <p>
    <%= form.label :Anonymous_author %><br>
    <%= form.text_field :anonymous_author %>
  </p>

  <p>
    <%= form.label :Content %><br>
    <%= form.text_area :content %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>
<%= link_to 'Clique pour suprimer', @gossip, method: :delete %>

<%= link_to 'Listes des gossips ', gossips_path %>

app/views/gossips/index.html.erb
<h1>Listes des Gossips</h1>
<% @gossips.each do |gossip| %>
  <p><%= "Auteur : " %> <strong> <%= gossip.anonymous_author.to_s %></strong>
  <%= "Contenu : "%> <strong> <%= gossip.content.to_s %></strong>
  <%= link_to "[Lire]", edit_gossip_path(gossip) %>
  <%= link_to "[Editer]", edit_gossip_path(gossip) %>
  </p>
<% end %>
<p><%= link_to "Créer un gossip", new_gossip_path%></p>

app/views/gossips/new.html.erb
<h1>Nouveau Gossip</h1>
<%= form_for @gossip, url: {action: "create"} do |gossip_form| %>
  <p><%= gossip_form.label :Anonymous_author %>:
  <%= gossip_form.text_field :anonymous_author %></p>
  <p><%= gossip_form.label :content %>:
  <%= gossip_form.text_field :content %></p>
  <p><%= gossip_form.submit "Créer" %></p>
<% end %>

app/views/gossips/show.html.erb
<h1>Gossip n° <%= @gossip.id %></h1>
<p>Auteur anonyme:<strong> <%= @gossip.anonymous_author %></strong></p>
<p>contenu:  <strong><%= @gossip.content %></strong></p>
<%= link_to "Listes gossips", gossips_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <link rel="stylesheet" href="http://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-1.2.8.min.css"/>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>